# Generated by Django 5.0.6 on 2024-05-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_member_reportcount_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='ChatApp.member')),
                ('reported_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ChatApp.member')),
            ],
            options={
                'unique_together': {('reported_member', 'reported_by')},
            },
        ),
    ]
