# Generated by Django 5.0.6 on 2024-05-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
