# Generated by Django 5.0.6 on 2024-05-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0005_rename_status_member_isonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='isOnline',
            field=models.BooleanField(default=True),
        ),
    ]
